### ISSUE TITLE
Despliegue de Api amazon_core a producción asociada a POLUX

### ISSUE THREAD

**Issue by mantnicot** [udistrital/core_amazon_crud#13]
Se requiere realizar el despliegue del API core_amazon_crud, por lo cual se debe realizar el llenado de la lista de despliegue planteada en los lineamientos de la OAS:
 

- [ ] Lista de despliegue

**Comment by mantnicot** [comment]
Se revisa de primera instancia que partes cumple el API para el desarrollo del despliegue

[Lineamientos despliegue core_amazon_crud.xlsx](https://github.com/udistrital/core_amazon_crud/files/7412169/Lineamientos.despliegue.core_amazon_crud.xlsx)

**Comment by a52290451** [comment]
Se debe registrar el cambio de API core_amazon_crud por parametros.

**Comment by mantnicot** [comment]
Se agrego los parametros directamente en el programa como reemplazo de la API core_amazon_crud

![Captura de pantalla de 2021-11-05 09-20-35](https://user-images.githubusercontent.com/85162258/140525306-29b55fec-f9c2-4a34-867a-b34fcb7e6831.png)
